DEF LOCALE_FIELD EQU 0;
DEF LOCALE_SWAMP EQU 1;

; is it better to hardcode everything so that music and enemy encounters are tied directly to Location, or should it be overrideable
; arg decisions

; what would be more work.
;  it would certainly be ... weirder to have music and enemies tied to warps. it wouldn't be suuuuuuper redundant. it would add _some_ flexibility, like
;      - having an area where getting there a particular way produces a different encounter table. or where the music is different.
;		 damn that sounds maybe very cool. like if a zone empties out? maybe it is cooler to just have it tied to warps

