INCLUDE "src/constants/gfx_constants.inc"

SECTION "Palette Data", ROMX

; BG palettes
OWPaletteSet::
	RGB 4,4,4, 2,11,6, 16,7,8,  15,12,8 ; z = 0
	RGB 4,4,4, 1,10,6, 15,6,7,  14,11,8 ; z = 1
	RGB 4,4,4, 1,10,6, 14,5,6,  13,10,8 ; z = 2
	RGB 4,4,4, 0,8,6,  13,4,5,  12,9,8  ; z = 3
	RGB 4,4,4, 0,7,6,  12,3,4,  11,8,8  ; unused
	RGB 0,0,0, 0,0,0,  0,0,0,   0,0,0   ; unused
	RGB 0,0,0, 0,0,0,  0,0,0,   0,0,0   ; unused
	RGB 0,0,0, 0,0,0,  0,0,0,   0,0,0   ; unused
	RGB 0,0,0, 0,0,0,  0,0,0,   0,0,0   ; unused
