SECTION "Tile Data", ROMX

; bg bank 0
BgBank0Tiles::
OWTiles::
INCBIN "build/gfx/explore-simple.2bpp"
OWTilesEnd::

ModalTiles::
INCBIN "build/gfx/modal-simple.2bpp"
ModalTilesEnd::

EncounterTiles::
INCBIN "build/gfx/encounter-simple.2bpp"
EncounterTilesEnd::

DistanceFogTiles::
INCBIN "build/gfx/distance-fog.2bpp"
DistanceFogTilesEnd::

EncounterEnvTreesTiles::
INCBIN "build/gfx/encounter-env-trees.2bpp"
EncounterEnvTreesTilesEnd::
BgBank0TilesEnd::


; bg bank 1
ScribTiles::
INCBIN "build/gfx/scrib.2bpp"
ScribTilesEnd::


; sprites bank 0
CompassTiles::
INCBIN "build/gfx/compass.2bpp"
CompassTilesEnd::

DangerIndicatorTiles::
INCBIN "build/gfx/danger-indicator.2bpp"
DangerIndicatorTilesEnd::

ChinchillaTiles::
INCBIN "build/gfx/chinchilla.2bpp"
ChinchillaTilesEnd::

ItemTiles::
INCBIN "build/gfx/item-tiles.2bpp"
ItemTilesEnd::
