AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal CloudFormation template to launch an EC2 instance.

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow traffic from specific IP
      VpcId: !Ref VPCId # You need to specify your VPC ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 146.115.74.202/32

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0 # Replace with the latest Amazon Linux AMI ID for your region
      KeyName: !Ref KeyName # You need to specify your EC2 Key Pair name
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: tutorial-ec2-instance-web-server-ad

Parameters:
  VPCId:
    Type: String
    Description: The ID of the VPC where the instance will be launched.
    
  KeyName:
    Type: String
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.
